DROP VIEW MSTR_LNKD_CONNECTIONS;

/* Formatted on 10/08/2012 10:57:19 (QP5 v5.139.911.3011) */
CREATE OR REPLACE FORCE VIEW MSTR_LNKD_CONNECTIONS
(
   CONNECTION_ID,
   CONNECTION_FIRST_NAME,
   CONNECTIONLAST_NAME,
   CONNECTION_HEADLINE
)
AS
   SELECT "ID",
          "FIRST_NAME",
          "LAST_NAME",
          "HEADLINE"
     FROM TABLE (mstr_lnkd_FFSQL.connections_table (SYS_CONTEXT ('eurostat_context', 'user')));
